name: Beta

on:
  push:
    branches: [ main ]
  schedule: 
    - cron: '0 0 16 * *'

jobs:
  Swiftlint: 
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v2
      - name: GitHub Action for SwiftLint with --strict
        uses: norio-nomura/action-swiftlint@3.1.0
        with:
          args: --strict
  Test:
    needs: SwiftLint
    runs-on: macos-latest
    steps:
    - name: Update Xcode version
      uses: maxim-lobanov/setup-xcode@v1.1
      with:
        xcode-version: latest-stable
    - name: Git checkout
      uses: actions/checkout@v2
    - name: Test
      run: fastlane test
  Beta:
    needs: Test
    runs-on: macos-latest
    steps:
    - name: Update Xcode version
      uses: maxim-lobanov/setup-xcode@v1.1
      with: 
        xcode-version: latest-stable
    - name: Git checkout
      uses: actions/checkout@v2
    - name: Update ssh agent
      uses: webfactory/ssh-agent@v0.4.1
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
    - name: Beta
      run: fastlane beta GITHUB_RUN_NUMBER:$GITHUB_RUN_NUMBER
      env:
        MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
        FASTLANE_PASSWORD: ${{ secrets.FASTLANE_PASSWORD }}
        FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD: ${{ secrets.FASTLANE_PASSWORD }}
        APPLE_ID: ${{ secrets.APPLE_ID }}
        ITC_TEAM_ID: ${{ secrets.ITC_TEAM_ID }}
        TEAM_ID: ${{ secrets.TEAM_ID }}
        API_KEY: ${{ secrets.API_KEY }}
        CERTIFICATES_GIT_URL: ${{ secrets.CERTIFICATES_GIT_URL }}
