name: Beta

on:
  pull_request

jobs:
  Swiftlint: 
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v2
      - name: GitHub Action for SwiftLint with --strict
        uses: norio-nomura/action-swiftlint@3.1.0
        with:
          args: --strict
      - name: GitHub Action for SwiftLint (Only files changed in the PR)
        uses: norio-nomura/action-swiftlint@3.1.0
        env:
          DIFF_BASE: ${{ github.base_ref }}
  Test:
    needs: SwiftLint
    runs-on: macos-latest
    steps:
    - name: Update Xcode version
      uses: maxim-lobanov/setup-xcode@v1.1
      with:
        xcode-version: latest-stable
    - name: Git checkout
      uses: actions/checkout@v2
    - name: Test
      run: fastlane test
